[jetCDNparse]
# the minimum amount of time after which the API will be synchronized (in minutes)
min-sync-delay-minutes = 43200 # 12 hours
# the useragent with which the API request will be made
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"

# prefix for all static files. It can be useful when the site is not deployed on a pure domain, but for example on /siteURI
# example:
# - /jetCDNparse
# - /githubPages
static-prefix = ""
