[project]
name = "jetCDNparse"
version = "0.1.0"
description = "a small JetBrains API parser"
readme = "README.md"
license = "WTFPL"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
    "environs>=15.0.1",
    "httpx[socks]>=0.28.1",
    "jinja2>=3.1.6",
]

[tool.ruff.format]
quote-style = 'single'
