name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v6
  
      - name: hello, uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
  
      - name: setup dependencies
        run: uv sync --all-extras
  
      - name: compile
        env:
          STATIC_PREFIX: "/jetCDNparse"
        run: cd jetCDNparse && uv run main.py --verbose

      - name: out deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages	
